### ISSUE TITLE
KeyErroer with sample if in self.getReadNumbers

### ISSUE THREAD

**Issue by flashton2003** [CDCgov/MaRS#3]
Hello,

I'm running MaRS within a conda virtual env with python 3.4. I get the following error when trying to run MaRS on some example data.

```
matplotlib 2.0.0
numpy 1.11.3
pysam 0.11.1
seaborn 0.7.1
pandas 0.19.2
Traceback (most recent call last):
  File "/home/ubuntu/programs/MaRS/pyamd/prepinputs.py", line 169, in prepInputs
    numreads = self.getReadNumbers(experiment[sample].files[0])
KeyError: 'SRR7853847'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pyamd.py", line 405, in <module>
    java_def)
  File "pyamd.py", line 223, in marsBatch
    config = prep.prepInputs()
  File "/home/ubuntu/programs/MaRS/pyamd/prepinputs.py", line 173, in prepInputs
    experiment[sample] = Sample(sample, lib, seqType, [fastq], libType, paired, numreads)
UnboundLocalError: local variable 'lib' referenced before assignment
```

My command line is
`sh run.sh /home/ubuntu/public_data/fastqs/ /home/ubuntu/public_data/output`

And the contents of `fastqs` dir is this

```/home/ubuntu/public_data/fastqs/
├── SRR7853847_1.fastq.gz
└── SRR7853847_2.fastq.gz
```

**Comment by eldin-talundzic** [comment]
Thank you for reaching out.

We have an updated version of the tool available. We haven’t merged it yet with the master. However, you can access it here: https://github.com/eldin-talundzic/NeST

The instructions are in the link and it sets up a condo env for you, including downloading the necessary dependencies you need.

Kind regards,

Eldin
_____________________________________________

Eldin Talundzic, Ph.D.

Health Scientist (Informatics)  | DPDM AMD Laboratory
Center for Disease Control and Prevention |
Division of Parasitic Diseases and Malaria (DPDM)
DDPHSIS/Center for Global Health (CGH)

1600 Clifton Rd, Atlanta, GA 30329
M: 706.363.2226 | W: 404.718.4403
etalundzic@cdc.gov<mailto:etalundzic@cdc.gov>


[cid:88de8bc4-8dd9-44db-b30b-6690b59cc686@cdc.gov]

On Dec 6, 2018, at 6:30 AM, flashton2003 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,

I'm running MaRS within a conda virtual env with python 3.4. I get the following error when trying to run MaRS on some example data.

matplotlib 2.0.0
numpy 1.11.3
pysam 0.11.1
seaborn 0.7.1
pandas 0.19.2
Traceback (most recent call last):
  File "/home/ubuntu/programs/MaRS/pyamd/prepinputs.py", line 169, in prepInputs
    numreads = self.getReadNumbers(experiment[sample].files[0])
KeyError: 'SRR7853847'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pyamd.py", line 405, in <module>
    java_def)
  File "pyamd.py", line 223, in marsBatch
    config = prep.prepInputs()
  File "/home/ubuntu/programs/MaRS/pyamd/prepinputs.py", line 173, in prepInputs
    experiment[sample] = Sample(sample, lib, seqType, [fastq], libType, paired, numreads)
UnboundLocalError: local variable 'lib' referenced before assignment


My command line is
sh run.sh /home/ubuntu/public_data/fastqs/ /home/ubuntu/public_data/output

And the contents of fastqs dir is this

├── SRR7853847_1.fastq.gz
└── SRR7853847_2.fastq.gz

**Comment by leebrian** [comment]
When you merge these changes into MaRS, will you also update the dependencies to clear the existing warnings? Or would it help me to open a separate issue for the vulnerabilities?

**Comment by eldin-talundzic** [comment]
The warnings are related to the team website and it’s dependencies it looks like. Let me do some house cleaning. If I can’t resolve it today, we can open up a issue ticket.


Kind regards,

Eldin Talundzic, Ph.D.

Health Scientist (Informatics) | DPDM AMD Laboratory
Center for Disease Control and Prevention |
DDPHSIS/Center for Global Health
Division of Parasitic Diseases and Malaria (DPDM)


1600 Clifton Rd, Atlanta, GA 30329
M: 706.363.2226 | W: 404.718.4403
etalundzic@cdc.gov

“It was once said that the moral test of government is how that government treats those who are in the dawn of life, the children; those who are in the twilight of life, the elderly; and those who are in the shadows of life, the sick, the needy and the handicapped.” - Hubert H. Humphrey




On Thu, Dec 6, 2018 at 7:10 AM -0500, "Brian Lee" <notifications@github.com<mailto:notifications@github.com>> wrote:


When you merge these changes into MaRS, will you also update the dependencies to clear the existing warnings? Or would it help me to open a separate issue for the vulnerabilities?
